include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - cancel_subscriptions
    - prefer_single_quotes
    - avoid_returning_null_for_future
    - prefer_void_to_null
    - always_require_non_null_named_parameters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - prefer_initializing_formals
    - prefer_typing_uninitialized_variables


analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true


# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
