name: dart_lnurl
description: A Dart implementation of the LNURL specification.
version: 0.2.1
repository: https://github.com/saentari/dart_lnurl

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bech32: ^0.2.1
  bip32: ^2.0.0
  ecdsa: ^0.0.4
  encrypt: ^5.0.1
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
